### ISSUE TITLE
render markdown inside <details> ?

### ISSUE THREAD

**Issue by noformnocontent** [markdown/markdown.github.com#16]
sidenote: not sure where should i post issues about markdown rendering engine which is used on github itself
here is the example:

w/o extra newline after the `<details>`:

<details>
# H1
* list element 1
* list element 2
</details>

----

with extra newline after the `<details>`:
<details>

# H1
* list element 1
* list element 2
</details>

**Comment by davidchambers** [comment]
GitHub Flavored Markdown now has a [spec][1].


[1]: https://github.github.com/gfm/

**Comment by noformnocontent** [comment]
yet https://github.com/github/gfm is a private repo (404 in my case) so i cant post this issue there

**Comment by waylan** [comment]
This is a community controlled account not related to any specific implementation. We have no control of or access to https://github.com/github/gfm. And we have no way of knowing if any of the developers of that project even follow this account. In other words, the people who you want to reach will probably not see it here. Perhaps you should report the issue to GitHub support.
